Handle case where sendto fails on interface that does not support it.
andreikop/python-ws-discovery pull request #42
Opened 2021-05-22 03:56 UTC by tom24

This can be because the interface is a VPN tunnel or is DOWN.

2021-05-23 10:11 UTC, petri commented on wsdiscovery/threaded.py
> +                    # In either just log as debug and ignore the error.
I guess this is supposed to say "In either case" (just log...)

2021-05-23 10:12 UTC, petri requested changes
Seems good to me. There's just a small typo I guess in docstr.

2021-05-23 13:00 UTC, tom24 commented
I corrected the typo.

2021-05-25 11:18 UTC, merged

2021-05-25 11:19 UTC, andreikop commented
Thank you!

2022-03-16 11:20 UTC, yateya commented
Thanks for fixing this bug. Will it be released to [pypi repo](https://pypi.org/project/WSDiscovery) soon?

2022-05-05 14:11 UTC, andreikop commented
@yateya , well, not soon, but it is released now.